api/urls.py
from django.contrib import admin
from django.urls import path, include

# Static and Media URLs config
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls")),
    path("v1/", include("posts.api.api_urls")),

    # CKEDITOR URLs
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


# Static and Media urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"

urlpatterns = [
    path("", views.home_page, name="home_page"),
    path("single-post/<str:id>/", views.single_post_page, name="single_post"),
    path("create-post/", views.create_post_page, name="create_post"),

    # Auth URLs
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = RichTextField(max_length=200)
    date_created = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.title

posts/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class UserCreateForm(UserCreationForm):
    """
    A form that inherits from the base *UserCreationForm*,
    and creates a user, with no privileges, from the given
    username and password.
    """
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword1',
        }),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword2',
            'required': 'true',
            'placeholder': 'Confirm Password*'
        }
        ),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',
                  'username', 'password1', 'password2']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'first_name',
                'required': 'true'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'first_name',
                'required': 'true'
            }),
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'email_address',
                'required': 'true'
            }),
            'username': forms.TextInput(attrs={
                'autocomplete': 'username',
                'class': 'form-control',
                'id': 'username',
                'required': 'true'
            }),
        }

posts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from .models import Post
from .forms import User, UserCreateForm

URL = "https://datavault-blog.herokuapp.com"


def home_page(request: HttpResponse) -> HttpResponse:

    context = {
        "url": URL
    }
    return render(request, "posts/index.html", context)


def single_post_page(request: HttpRequest, id) -> HttpResponse:
    post = Post.objects.get(id=id)

    context = {
        "post": post,
        "url": URL
    }
    return render(request, "posts/single-post.html", context)


@login_required(login_url="/login/")
def create_post_page(request: HttpRequest) -> HttpResponse:
    context = {
        "url": URL
    }
    return render(request, "posts/create-post.html", context)


def register_user(request: HttpRequest) -> HttpResponse:
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        print(form.is_valid)

        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")
            return redirect("posts:login")

    context = {"form": form}
    return render(request, "auth/register.html", context)


def login_user(request: HttpRequest) -> HttpResponse:
    username = request.POST.get("username")
    password = request.POST.get("password")

    if request.method == "POST":

        user = authenticate(username=username, password=password)
        if user.is_active:
            login(request, user)
            messages.success(
                request, f"Welcome {username}, you are logged in.")
            return redirect('posts:home_page')

    context = {}
    return render(request, "auth/login.html", context)


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "Logged out successfully!")
    return redirect('posts:home_page')

templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>DataVault Blog</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static "css/vendor.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--  ================================================== -->
    <script src="{% static "js/modernizr.js" %}"></script>
    <script defer src="{% static "js/fontawesome/all.min.js" %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon-16x16.png" %}">

</head>

<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="container">


            <div class="s-header__logo">
                <a class="logo" href="{% url "posts:home_page" %}">
                    <img src="{% static "images/logo.svg" %}" alt="Homepage">
                </a>
            </div>

            <div class="row s-header__navigation">

                <nav class="s-header__nav-wrap">

                    <h3 class="s-header__nav-heading h6">Navigate to</h3>

                    <ul class="s-header__nav">
                        <li class="current"><a href="{% url "posts:home_page" %}">Home</a></li>

                        {% if request.user.is_authenticated %}
                        <li><a href="{% url "posts:create_post" %}">Create Post</a></li>
                        <li><a href="{% url "posts:logout" %}" title="">Logout</a></li>
                        {% else %}
                        <li><a href="{% url "posts:register" %}" title="">Register</a></li>
                        <li><a href="{% url "posts:login" %}" title="">Login</a></li>
                        {% endif %}

                    </ul> <!-- end s-header__nav -->

                    <a href="#0" title="Close Menu" class="s-header__overlay-close close-mobile-menu">Close</a>

                </nav>

            </div> <!-- end s-header__navigation -->

            <a class="s-header__toggle-menu" href="#0" title="Menu">
                <span>Menu</span>
            </a>

        </div>

    </header> <!-- end s-header -->

    {% block content %}

    {% endblock content %}



    <!-- Java Script
    ================================================== -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

    <script src="{% static "js/jquery-3.5.0.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static "js/plugins.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>


    {% block inline_js %}{% endblock inline_js %}

</body>

</html>

templates/posts/create-post.html
{% extends "auth/base.html" %}
{% load static %}

{% block title %}
Create Post
{% endblock title %}

{% block content %}
<h2 class="register__innetext">Create Post</h2>

<p class="alert alert-success d-none" id="success_post"></p>

<form id="create-new-post-form" method="POST" class="card post__card">
    {% csrf_token %}

    <div class="form-group col-12">
        <label for="title">
            Title
        </label>
        <input class="form-control create_title" type="text" placeholder="Title of post" name="title" id="post__title">
    </div>

    <!-- <div class="form-group mt-5">
        <div class="mb-3">
                        <label for="formFile" class="form-label">Image:</label>
                        <input class="form-control" type="file" accept="image/png, image/jpeg, image/jpg"
                            id="post_image">
                    </div>
    </div> -->

    <div class="form-group col-12">
        <div class="mb-3">
            <label for="content">Content</label>
            <textarea class="form-control create_content" id="post_content" rows="3"
                placeholder="Post content. . ."></textarea>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Create Post</button>

</form>

{% endblock content %}


{% block inline_js %}

<script>
    const postForm = document.getElementById("create-new-post-form");
    const postTitle = document.getElementById("post__title");
    const postContent = document.getElementById("post_content");

    // Success Message Variable
    const successMsg = document.getElementById("success_post");

    const url = "{{ url }}/v1/api/";

    var postData = {
        "title": "",
        "author": "",
        "content": ""
    }

    // Form Submit Event Listener
    postForm.addEventListener("submit", (e) => {

        // Prevent Default submit behavior of form
        e.preventDefault();

        // Prepopulates post data with data coming from the form
        postData.title = postTitle.value;
        postData.content = postContent.value;
        postData.author = parseInt("{{ request.user.id }}");

        // Prints the post data to the browser console
        console.log(postData);

        // Axios handles POST request by submit data to the server
        axios({
                method: "POST",
                url: url,
                xstfCookieName: "csrftoken",
                xsrfHeaderName: "X-CSRFToken",
                data: JSON.stringify(postData),
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': "csrftoken",
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(res => {

                if (res.status === 201 && res.statusText === "Created") {
                    successMsg.classList.remove("d-none");
                    successMsg.innerText = res.data.message;

                    // Takes user back to home page
                    window.location.href = "{% url 'posts:home_page' %}"
                }

            }).catch(err => {
                console.log(err);
            })
    })
</script>

{% endblock inline_js %}

templates/posts/index.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
<!-- hero
    ================================================== -->
<section id="hero" class="s-hero">

    <style>
        div.blog__content {
            max-width: 90% !important;
        }

        a.create__post {
            font-size: 18px;
            color: inherit !important;
            font-family: inherit !important;
            text-decoration: none !important;
            text-transform: uppercase;
            margin-right: 10px;
        }

        span.cat-links>a,
        h1.s-hero__slide-text {
            text-decoration: none !important;
        }
    </style>

    <div class="s-hero__slider">

        <div class="s-hero__slide">

            <div class="s-hero__slide-bg" style="background-image: url('images/slide1-bg-3000.jpg');"></div>

            <div class="row s-hero__slide-content blog__content animate-this">
                <div class="column">
                    <div class="s-hero__slide-meta">
                        <span class="cat-links">
                            <a href="#0">
                                Data Science
                            </a>
                            <a href="#0">Largest Blog About Data Science</a>
                        </span>
                    </div>
                    <h1 class="s-hero__slide-text">
                        <a href="#0">
                            Blog By DataVault
                        </a>
                    </h1>
                </div>
            </div>

        </div> <!-- end s-hero__slide -->

    </div> <!-- end s-hero__slide -->

    <div class="s-hero__social hide-on-mobile-small">
        <ul class="s-hero__social-icons">
            <li><a href="#0"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
            <li><a href="#0"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#0"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href="#0"><i class="fab fa-dribbble" aria-hidden="true"></i></a></li>
        </ul>
    </div> <!-- end s-hero__social -->

    <div class="nav-arrows s-hero__nav-arrows">
        <button class="s-hero__arrow-prev">
            <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                <path d="M1.5 7.5l4-4m-4 4l4 4m-4-4H14" stroke="currentColor"></path>
            </svg>
        </button>
        <button class="s-hero__arrow-next">
            <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                <path d="M13.5 7.5l-4-4m4 4l-4 4m4-4H1" stroke="currentColor"></path>
            </svg>
        </button>
    </div> <!-- end s-hero__arrows -->

    <!-- Messages -->
    <div class="messages" id="messages">
        {% if messages %}
        {% for message in messages %}
        <div class="mt-3 alert alert-success">
            <h5 class="m-0">
                {{ message }}
            </h5>
        </div>
        {% endfor %}
        {% endif %}
    </div>

</section> <!-- end s-hero -->


<!-- content
    ================================================== -->
<section class="s-content s-content--no-top-padding">


    <!-- masonry
        ================================================== -->
    <div class="s-bricks">

        <div class="masonry">
            <div class="bricks-wrapper h-group">

                <div class="grid-sizer"></div>

                <div class="lines">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

                <div id="blog_posts"></div>

            </div>
            <!-- end brick-wrapper -->

        </div> <!-- end masonry -->

    </div> <!-- end s-bricks -->

</section> <!-- end s-content -->

{% endblock content %}

{% block inline_js %}

<script>
    const posts = document.getElementById("blog_posts");
    const url = "{{ url }}/v1/api/";
    const singleBlogUrl = "{{ url }}/single-post"

    axios({
        method: "GET",
        url: url,
        xstfCookieName: "csrftoken",
        xsrfHeaderName: "X-CSRFToken",
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': 'csrftoken',
            'X-Requested-With': 'XMLHttpRequest'

        }
    }).then(res => {
        res = res.data;

        // Loop through each blog post
        res.map(post => {
            posts.innerHTML += `<article class="brick entry" style="">

                <div class="entry__text">
                    <div class="entry__header">
                        <h1 class="entry__title">
                            <a href="${singleBlogUrl}/${post.id}/">
                                ${post.title}
                            </a>
                        </h1>
                    </div>
                    <div class="entry__excerpt">
                        <p>
                            ${post.content}
                        </p>
                    </div>
                    <a class="entry__more-link" href="${singleBlogUrl}/${post.id}/">Learn More</a>
                </div>

            </article>`

            console.log(post.id);
            console.log(post.title);
            console.log(post.image);
            console.log(post.content);
        })
    })
</script>

{% endblock inline_js %}

templates/posts/single-post.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
<style>
    article.post_card {
        margin-top: 200px;
        padding: 20px;
        border-radius: 50px;
    }

    div.single_post_header>h1 {
        margin-bottom: 20px;
        padding-top: 20px;
    }

    div.s-content__entry-content>p,
    div.s-content__entry-content {
        font-size: 14px !important;
        text-align: center !important;
    }

    @media screen and (max-width: 786px) {
        article.post_card {
            margin-top: 200px !important;
        }
    }
</style>
<section class="single_post">
    <div class="container">
        <article class="card post_card">

            <div class="single_post_header">
                <h1 class="s-content__title s-content__title--post">{{ post.title }}</h1>
            </div> <!-- end s-content__entry-header -->

            <div class="s-content__primary">

                <div class="s-content__entry-content">

                    {{ post.content|safe }}

                </div> <!-- end s-entry__entry-content -->

                <div class="s-content__entry-meta">

                    <div class="entry-author meta-blk">
                        <div class="byline">
                            <span class="bytext">Posted By</span>
                            <a href="#0">{{ post.author.username }}</a>
                        </div>
                    </div>

                    <div class="meta-bottom">

                        <div class="entry-cat-links meta-blk">

                            <span>On</span>
                            {{ post.date_created }}
                        </div>

                    </div>

                </div> <!-- s-content__entry-meta -->

            </div> <!-- end s-content__primary -->
        </article>
    </div>
</section>
{% endblock content %}